import { lazy, Suspense } from 'react';
import { useParams, Link, Navigate } from 'react-router-dom';
import BlogLayout from '../components/BlogLayout';
import { getPost } from '../data/blogPosts';
import { useApi } from '../hooks/useApi.js';
import s from './BlogPost.module.css';

const CONTENT_MAP = {
  'healthcare-price-transparency': lazy(() =>
    import('./blog/HealthcarePriceTransparency')
  ),
};

function ArticleLoader() {
  return (
    <div className={s.loading}>
      <div className={s.loadingBar} />
    </div>
  );
}

export default function BlogPost() {
  const { slug } = useParams();
  const staticPost = getPost(slug);

  // Only fetch from DB if not a static post
  const { data: dbPost, loading, error } = useApi(
    staticPost ? null : `/blog/${slug}`,
    [slug],
  );

  // Static editorial post
  if (staticPost) {
    const ContentComponent = CONTENT_MAP[slug];
    return (
      <BlogLayout>
        <div className={s.masthead}>
          {staticPost.tags.join(' · ')}
        </div>
        <header className={s.hero}>
          <div className={s.kicker}>{staticPost.kicker}</div>
          <h1 className={s.title}>{staticPost.title}</h1>
          <p className={s.subtitle}>{staticPost.subtitle}</p>
          <p className={s.byline}>
            <strong>{staticPost.byline}</strong>
            <span className={s.bylineSep}>&middot;</span>
            {staticPost.date}
            <span className={s.bylineSep}>&middot;</span>
            {staticPost.readTime}
          </p>
        </header>
        <div className={s.articleWrap}>
          {ContentComponent ? (
            <Suspense fallback={<ArticleLoader />}>
              <ContentComponent />
            </Suspense>
          ) : (
            <p className={s.notFound}>Article content not found.</p>
          )}
        </div>
        <div className={s.articleFooter}>
          <p>
            <strong>About this investigation.</strong> MediCosts is an ongoing project
            to aggregate and make accessible the pricing data published under the
            Transparency in Coverage Rule. The findings reported here are based on direct
            technical testing of insurer endpoints conducted between 2024 and 2025.
            Methodology details and raw accessibility data are available upon request.
          </p>
          <div className={s.backRow}>
            <Link to="/blog" className={s.backLink}>&larr; All Posts</Link>
          </div>
        </div>
      </BlogLayout>
    );
  }

  // Loading DB post
  if (loading) return <BlogLayout><ArticleLoader /></BlogLayout>;

  // Not found
  if (error || !dbPost) return <Navigate to="/blog" replace />;

  // DB-sourced daily report
  const pubDate = new Date(dbPost.published_at).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  return (
    <BlogLayout>
      <div className={s.masthead}>
        {(dbPost.tags || []).join(' · ')}
      </div>
      <header className={s.hero}>
        <div className={s.kicker}>ClearNetwork Daily Report</div>
        <h1 className={s.title}>{dbPost.title}</h1>
        <p className={s.subtitle}>{dbPost.summary}</p>
        <p className={s.byline}>
          <strong>ClearNetwork Crawler</strong>
          <span className={s.bylineSep}>&middot;</span>
          {pubDate}
        </p>
      </header>
      <div className={s.articleWrap}>
        <div
          className={s.dbContent}
          dangerouslySetInnerHTML={{ __html: dbPost.content_html }}
        />
      </div>
      <div className={s.articleFooter}>
        <p>
          <strong>About this report.</strong> This report is auto-generated by the
          ClearNetwork crawler, part of the{' '}
          <a href="https://medicosts.acumenus.net">MediCosts</a> open healthcare data
          project. Data is collected nightly from publicly available sources required
          under the Transparency in Coverage Rule.
        </p>
        <div className={s.backRow}>
          <Link to="/blog" className={s.backLink}>&larr; All Posts</Link>
        </div>
      </div>
    </BlogLayout>
  );
}
